---
title: "Chemical stat figures"
author: "Erika Walker"
date: "`r Sys.Date()`"
output: html_document
---

Purpose: create barplot and scatterplot of % above LOD stats for each chemical

Adapting from Lauren's code: https://github.com/bakulskilab/NHANES_Chemicals_MCI/blob/main/f%20-%20lod_figures.R

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggrepel)
```

# Load data
```{r}
chem_stats <- read_csv('Output Cog ExWAS/Chem descriptive stats May 15 2024.csv')
```

# Prep data
```{r}
# remove units from chem names
chem_stats$variable_description_use <- gsub('\\s\\(([^()]+)\\)$', 
                                            '',
                                            chem_stats$variable_description_use)

# pull LOD variable info and turn into long dataset
chem_stats_long <- chem_stats %>%
  select(chem_name, variable_description_use, chemical_family, 
         n, n_above_lod, n_below_lod, pct_above_lod) %>%
  pivot_longer(cols = n_above_lod:n_below_lod,
               values_to = 'count',
               names_to = 'over_under')

# colors for bars
mycolors <- c('darkmagenta', 'grey50')

```

# Barplot

Bar length = N measures; color fill split by above/below LOD
```{r}
chem_by_partic_by_LOD <- ggplot(data = chem_stats_long,
                                aes(x = count,
                                    y = reorder(variable_description_use, count))) +
  geom_col(aes(fill = over_under), 
           width = 0.6,
           position = position_stack(reverse = TRUE)) +
  labs(x = 'Participants', y = '') +
  scale_fill_manual(values = mycolors,
                    name = 'Limit of Detection (LOD)',
                    labels = c('N above LOD',
                               'N below LOD')) +
  scale_x_continuous(expand = c(0, 0)) +
  theme_light() +
  theme(axis.text.y = element_text(size = 4),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color = 'grey87',
                                          linewidth = rel(0.5)),
        panel.grid.minor.x = element_line(color = 'grey87',
                                          linewidth = rel(0.25)))

chem_by_partic_by_LOD

```

# Scatterplot

Plot N measures vs % above LOD
```{r}
# sort chemical families in alpha order
chem_family_alpha <- chem_stats %>%
  select(chemical_family) %>%
  arrange(chemical_family) %>%
  unique()

chem_family_order <- chem_family_alpha$chemical_family

# apply order to chem_stats
chem_stats$chemical_family <- factor(chem_stats$chemical_family,
                                     levels = chem_family_order)

# colors
chem_fam_colors <- c("#FFB6C1", # Acrylamide
                     "#9b870c", # Aldehydes
                     "#EE0000", # Aromatic amines
                     #"#FF6B00", # BFRs
                     #"#7D26CD", # Dietary components
                     "#FFA500", # Dioxins
                     #"#BABABA", # Furans
                     #"#EEEE00", # Melamine
                     "#228B22", # Metals
                     "#A4D3EE", # PFAS
                     "#A2CD5A", # Personal Care
                     "#1E90FF", # Pesticides
                     "#be67c9", # PFRs
                     "#FF69B4", # Phthalates
                     #"#cf9b76", # Phytoestrogens
                     "#828282", # PAHs
                     "#8B4513", # PCBs
                     "#8B0000", # Smoking related compounds
                     "#0E1171") # VOCs

# plot
scatter_partic_by_chem_LOD <- ggplot(chem_stats,
                                     aes(x = n,
                                         y = pct_above_lod,
                                         color = chemical_family)) +
  geom_point(size = 3) +
  scale_color_manual(name = 'Chemical Family', 
                     values = chem_fam_colors) +
  geom_text_repel(aes(label = ifelse(n > 2500, 
                                     as.character(variable_description_use), '')),
                  size = 3) +
  geom_text_repel(aes(label = ifelse(pct_above_lod < 55 & n < 10000,
                                     as.character(variable_description_use), '')),
                  size = 3) +
  labs(x = 'Participants',
       y = 'Percent Above LOD (%)') +
  theme_light() +
  theme(legend.position = 'bottom',
        legend.title = element_blank())

scatter_partic_by_chem_LOD

```

# Save plots
```{r}
# barplot
ggsave(filename = 'Output Cog ExWAS/Barplot of chem LOD stats May 31 2024.pdf',
       plot = chem_by_partic_by_LOD,
       width = 9,
       height = 9)

ggsave(filename = 'Output Cog ExWAS/Barplot of chem LOD stats May 31 2024.png',
       plot = chem_by_partic_by_LOD,
       width = 9,
       height = 9,
       dpi = 600) # trying to improve resolution when saving as an image, default dpi = 300

# scatterplot
ggsave(filename = 'Output Cog ExWAS/Scatterplot of chem N and LOD May 31 2024.pdf',
       plot = scatter_partic_by_chem_LOD,
       width = 14,
       height = 9)

ggsave(filename = 'Output Cog ExWAS/Scatterplot of chem N and LOD May 31 2024.png',
       plot = scatter_partic_by_chem_LOD,
       width = 14,
       height = 9,
       dpi = 600)

```



