---
title: "Cognition ExWAS plots"
author: "Erika Walker"
date: "2024-05-10"
output: html_document
---

Create volcano plots for cognition ExWAS analyses

Layer order: lines, then dots, then labels

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sjlabelled)
library(ggrepel)
```

# Load results files
```{r}
# main analysis
main <- read_csv('Output Cog ExWAS/Cog ExWAS main analysis model output chem term May 14 2024.csv')

# normal eGFR
normal_egfr <- read_csv('Output Cog ExWAS/Cog ExWAS normal eGFR model output chem term May 14 2024.csv')

# add lifestyle covariates
add_covars <- read_csv('Output Cog ExWAS/Cog ExWAS lifestyle model output chem term May 14 2024.csv')

# binary mild cognitive impairment
poisson <- read_csv('Output Cog ExWAS/Cog ExWAS poisson model output chem term May 14 2024.csv')

# binary, normal eGFR
poisson_egfr <- read_csv('Output Cog ExWAS/Cog ExWAS poisson normal eGFR model output chem term May 14 2024.csv')

```

# Set up chemical family colors
```{r}
# sort chemical families in alpha order
chem_family_alpha <- main %>%
  select(chemical_family) %>%
  arrange(chemical_family) %>%
  unique()

chem_family_order <- chem_family_alpha$chemical_family

chem_fam_colors <- c("#FFB6C1", # Acrylamide
                     "#9b870c", # Aldehydes
                     "#EE0000", # Aromatic amines
                     #"#FF6B00", # BFRs
                     #"#7D26CD", # Dietary components
                     "#FFA500", # Dioxins
                     #"#BABABA", # Furans
                     #"#EEEE00", # Melamine
                     "#228B22", # Metals
                     "#A4D3EE", # PFAS
                     "#A2CD5A", # Personal Care
                     "#1E90FF", # Pesticides
                     "#be67c9", # PFRs
                     "#FF69B4", # Phthalates
                     #"#cf9b76", # Phytoestrogens
                     "#828282", # PAHs
                     "#8B4513", # PCBs
                     "#8B0000", # Smoking related compounds
                     "#0E1171") # VOCs

```

# Main analysis
```{r}
# factor chem family
main <- main %>%
  mutate(chemical_family = factor(chemical_family,
                                  levels = chem_family_order)) 

# add labels
main <- main %>%
  mutate(chem_label = case_when(p_val_adj < 0.1 ~ gsub('\\s\\(([^()]+)\\)$', # remove units ' (__)' from the end of the name
                                                        '',
                                                        full_chem_name),
                                .default = ''))

# plot
volcano_plot_cog_exwas <- ggplot(main, 
                                 aes(x = estimate,
                                     y = -log10(p_val_adj), 
                                     label = chem_label,
                                     color = chemical_family)) +
  theme_light() +
  geom_hline(yintercept = -log10(0.05),
             linetype = 'dashed',
             color = 'red') + 
  geom_hline(yintercept = -log10(0.1), # adding additional line at p adj = 0.1
             linetype = 'dashed',
             color = 'blue') +
  geom_vline(xintercept = 0,
             linetype = 'dashed',
             color = 'black') +
  geom_point(size = 3) +
  # plot labels separately above and below the significance cutoff and nudge labels up or down accordingly
  geom_text_repel(data = subset(main, p_val_adj < 0.05),
                  nudge_y = 0.1,
                  size = 3,
                  max.overlaps = 20) + 
  geom_text_repel(data = subset(main, p_val_adj > 0.05),
                  nudge_y = -0.1,
                  size = 3,
                  max.overlaps = 20) + 
  scale_color_manual(values = chem_fam_colors) +
  xlim(-4.1, 2.5) +
  ylim(-0.1, 5) +
  xlab(expression('Difference in cognition score per 1 standard deviation increase of the log'[2] ~ 'scaled chemical measure')) +
  ylab(expression('-log'[10] ~ '(adjusted p value)')) +
  theme(legend.position = 'bottom',
        legend.title = element_blank(),
        legend.text = element_text(size = 7.5))

volcano_plot_cog_exwas 

ggsave(filename = 'Output Cog ExWAS/Cog ExWAS main analysis volcano plot May 28 2024.pdf',
       plot = volcano_plot_cog_exwas,
       height = 9,
       width = 14)

ggsave(filename = 'Output Cog ExWAS/Cog ExWAS main analysis volcano plot May 28 2024.png',
       plot = volcano_plot_cog_exwas,
       height = 9,
       width = 14)

```

## Normal eGFR subset
```{r}
# factor chem family
normal_egfr <- normal_egfr %>%
  mutate(chemical_family = factor(chemical_family,
                                  levels = chem_family_order)) 

# add labels
normal_egfr <- normal_egfr %>%
  mutate(chem_label = case_when(p_val_adj < 0.1 ~ gsub('\\s\\(([^()]+)\\)$',
                                                        '',
                                                        full_chem_name),
                                .default = ''))

# plot
volcano_plot_cog_exwas_egfr <- ggplot(normal_egfr, 
                                      aes(x = estimate,
                                          y = -log10(p_val_adj), 
                                          label = chem_label,
                                          color = chemical_family)) +
  theme_light() +
  geom_hline(yintercept = -log10(0.05),
             linetype = 'dashed',
             color = 'red') +
  geom_hline(yintercept = -log10(0.1), # adding additional line at p adj = 0.1
             linetype = 'dashed',
             color = 'blue') +
  geom_vline(xintercept = 0,
             linetype = 'dashed',
             color = 'black') +
  geom_point(size = 3) +
  # plot labels separately above and below the significance cutoff and nudge labels up or down accordingly
  geom_text_repel(data = subset(normal_egfr, p_val_adj < 0.05),
                  nudge_y = 0.07,
                  size = 3,
                  max.overlaps = 20) + 
  geom_text_repel(data = subset(normal_egfr, p_val_adj > 0.05),
                  nudge_y = -0.07,
                  size = 3,
                  max.overlaps = 20) + 
  scale_color_manual(values = chem_fam_colors) +
  xlim(-4.1, 2.5) +
  ylim(-0.1, 5) +
  xlab(expression('Difference in cognition score per 1 standard deviation increase of the log'[2] ~ 'scaled chemical measure, subsetted to participants with normal eGFR')) +
  ylab(expression('-log'[10] ~ '(adjusted p value)')) +
  theme(legend.position = 'bottom',
        legend.title = element_blank(),
        legend.text = element_text(size = 7.5))

volcano_plot_cog_exwas_egfr 

ggsave(filename = 'Output Cog ExWAS/Cog ExWAS normal eGFR volcano plot May 28 2024.pdf',
       plot = volcano_plot_cog_exwas_egfr,
       height = 9,
       width = 14)

ggsave(filename = 'Output Cog ExWAS/Cog ExWAS normal eGFR volcano plot May 28 2024.png',
       plot = volcano_plot_cog_exwas_egfr,
       height = 9,
       width = 14)

```

## Adding lifestyle covariates
```{r}
# factor chem family
add_covars <- add_covars %>%
  mutate(chemical_family = factor(chemical_family,
                                  levels = chem_family_order)) 

# add labels
add_covars <- add_covars %>%
  mutate(chem_label = case_when(p_val_adj < 0.1 ~ gsub('\\s\\(([^()]+)\\)$',
                                                        '',
                                                        full_chem_name),
                                .default = ''))

# plot
volcano_plot_cog_exwas_lifestyle <- ggplot(add_covars, 
                                      aes(x = estimate,
                                          y = -log10(p_val_adj), 
                                          label = chem_label,
                                          color = chemical_family)) +
  theme_light() +
  geom_hline(yintercept = -log10(0.05),
             linetype = 'dashed',
             color = 'red') +
  geom_hline(yintercept = -log10(0.1), # adding additional line at p adj = 0.1
             linetype = 'dashed',
             color = 'blue') +
  geom_vline(xintercept = 0,
             linetype = 'dashed',
             color = 'black') +
  geom_point(size = 3) +
  # plot labels separately above and below the significance cutoff and nudge labels up or down accordingly
  geom_text_repel(data = subset(add_covars, p_val_adj < 0.05),
                  nudge_y = 0.07,
                  size = 3,
                  max.overlaps = 20) + 
  geom_text_repel(data = subset(add_covars, p_val_adj > 0.05),
                  nudge_y = -0.07,
                  size = 3,
                  max.overlaps = 20) + 
  scale_color_manual(values = chem_fam_colors) +
  xlim(-4.1, 2.5) +
  ylim(-0.1, 5) +
  xlab(expression('Difference in cognition score per 1 standard deviation increase of the log'[2] ~ 'scaled chemical measure, adjusted further for waist circumference and alcohol consumption')) +
  ylab(expression('-log'[10] ~ '(adjusted p value)')) +
  theme(legend.position = 'bottom',
        legend.title = element_blank(),
        legend.text = element_text(size = 7.5))

volcano_plot_cog_exwas_lifestyle

ggsave(filename = 'Output Cog ExWAS/Cog ExWAS lifestyle covars volcano plot May 28 2024.pdf',
       plot = volcano_plot_cog_exwas_lifestyle,
       height = 9,
       width = 14)

ggsave(filename = 'Output Cog ExWAS/Cog ExWAS lifestyle covars volcano plot May 28 2024.png',
       plot = volcano_plot_cog_exwas_lifestyle,
       height = 9,
       width = 14)

```

## Binary MCI
```{r}
# factor chem family
poisson <- poisson %>%
  mutate(chemical_family = factor(chemical_family,
                                  levels = chem_family_order)) 

# add labels
poisson <- poisson %>%
  mutate(chem_label = case_when(p_val_adj < 0.1 ~ gsub('\\s\\(([^()]+)\\)$',
                                                        '',
                                                        full_chem_name),
                                .default = ''))

# plot
volcano_plot_cog_exwas_poisson <- ggplot(poisson, 
                                         aes(x = exp_est,
                                             y = -log10(p_val_adj), 
                                             label = chem_label,
                                             color = chemical_family)) +
  theme_light() +
  geom_hline(yintercept = -log10(0.05),
             linetype = 'dashed',
             color = 'red') +
  geom_hline(yintercept = -log10(0.1), # adding additional line at p adj = 0.1
             linetype = 'dashed',
             color = 'blue') +
  geom_vline(xintercept = 1,
             linetype = 'dashed',
             color = 'black') +
  geom_point(size = 3) +
  # plot labels separately above and below the significance cutoff and nudge labels up or down accordingly
  geom_text_repel(data = subset(poisson, p_val_adj < 0.05),
                  nudge_y = 0.07,
                  size = 3,
                  max.overlaps = 20) + 
  geom_text_repel(data = subset(poisson, p_val_adj > 0.05),
                  nudge_y = -0.07,
                  size = 3,
                  max.overlaps = 20) + 
  scale_color_manual(values = chem_fam_colors) +
  scale_x_continuous(trans = 'log10',
                     limits = c(0.5, 1.7),
                     breaks = seq(0.5, 1.7, by = 0.2)) +
  ylim(-0.1, 2.5) +
  xlab(expression('Relative risk of mild cognitive impairment per 1 standard deviation increase of the log'[2] ~ 'scaled chemical measure')) +
  ylab(expression('-log'[10] ~ '(adjusted p value)')) +
  theme(legend.position = 'bottom',
        legend.title = element_blank(),
        legend.text = element_text(size = 7.5))

volcano_plot_cog_exwas_poisson

ggsave(filename = 'Output Cog ExWAS/Cog ExWAS poisson volcano plot May 28 2024.pdf',
       plot = volcano_plot_cog_exwas_poisson,
       height = 9,
       width = 14)

ggsave(filename = 'Output Cog ExWAS/Cog ExWAS poisson volcano plot May 28 2024.png',
       plot = volcano_plot_cog_exwas_poisson,
       height = 9,
       width = 14)

```

## Binary outcome, normal eGFR
```{r}
# factor chem family
poisson_egfr <- poisson_egfr %>%
  mutate(chemical_family = factor(chemical_family,
                                  levels = chem_family_order)) 

# add labels
poisson_egfr <- poisson_egfr %>%
  mutate(chem_label = case_when(p_val_adj < 0.1 ~ gsub('\\s\\(([^()]+)\\)$',
                                                        '',
                                                        full_chem_name),
                                .default = ''))

# plot
volcano_plot_cog_exwas_poisson_egfr <- ggplot(poisson_egfr, 
                                         aes(x = exp_est,
                                             y = -log10(p_val_adj), 
                                             label = chem_label,
                                             color = chemical_family)) +
  theme_light() +
  geom_hline(yintercept = -log10(0.05),
             linetype = 'dashed',
             color = 'red') +
  geom_hline(yintercept = -log10(0.1), # adding additional line at p adj = 0.1
             linetype = 'dashed',
             color = 'blue') +
  geom_vline(xintercept = 1,
             linetype = 'dashed',
             color = 'black') +
  geom_point(size = 3) +
  # plot labels separately above and below the significance cutoff and nudge labels up or down accordingly
  geom_text_repel(data = subset(poisson_egfr, p_val_adj < 0.05),
                  nudge_y = 0.02,
                  size = 3,
                  max.overlaps = 20) + 
  geom_text_repel(data = subset(poisson_egfr, p_val_adj > 0.05),
                  nudge_y = -0.02,
                  size = 3,
                  max.overlaps = 20) + 
  scale_color_manual(values = chem_fam_colors) +
  scale_x_continuous(trans = 'log10',
                     limits = c(0.5, 1.7),
                     breaks = seq(0.5, 1.7, by = 0.2)) +
  ylim(-0.1, 2.5) +
  xlab(expression('Relative risk of mild cognitive impairment per 1 standard deviation increase of the log'[2] ~ 'scaled chemical measure, subsetted to participants with normal eGFR')) +
  ylab(expression('-log'[10] ~ '(adjusted p value)')) +
  theme(legend.position = 'bottom',
        legend.title = element_blank(),
        legend.text = element_text(size = 7.5))

volcano_plot_cog_exwas_poisson_egfr

ggsave(filename = 'Output Cog ExWAS/Cog ExWAS normal eGFR poisson volcano plot May 28 2024.pdf',
       plot = volcano_plot_cog_exwas_poisson_egfr,
       height = 9,
       width = 14)

ggsave(filename = 'Output Cog ExWAS/Cog ExWAS normal eGFR poisson volcano plot May 28 2024.png',
       plot = volcano_plot_cog_exwas_poisson_egfr,
       height = 9,
       width = 14)

```

# Additional plot: forest plot of all main analysis results for supplement
```{r}
# remove units from names
main$full_chem_name <- gsub('\\s\\(([^()]+)\\)$',
                            '',
                            main$full_chem_name)

forest_plot <- ggplot(data = main,
                      aes(x = estimate,
                          y = reorder(full_chem_name, -estimate), # sort by direction of estimate
                          xmin = ci_lower,
                          xmax = ci_upper,
                          color = chemical_family)) +
  theme_light() +
  geom_vline(xintercept = 0,
             linetype = 2) +
  geom_pointrange(aes(col = chemical_family),
                  position = position_dodge2(width = 1),
                  size = 0.3) +
  scale_color_manual(values = chem_fam_colors) +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 3.5)) +
  theme(legend.position = 'bottom',
        legend.title = element_blank(),
        legend.text = element_text(size = 7.5)) +
  xlab(expression('Difference in cognition score per 1 standard deviation increase of the log'[2] ~ 'scaled chemical measure')) +
  ylab('') +
  scale_x_continuous(limits = c(-6, 6),
                     breaks = c(-6, -4, -2, 0, 2, 4, 6))

forest_plot

ggsave(filename = 'Output Cog ExWAS/Cog ExWAS main analysis forest plot May 28 2024.pdf',
       plot = forest_plot,
       height = 9,
       width = 14)

ggsave(filename = 'Output Cog ExWAS/Cog ExWAS main analysis forest plot May 28 2024.png',
       plot = forest_plot,
       height = 9,
       width = 14)

```


